# .github/workflows/build.yml
name: Build PostgreSQL with zhparser

on:
  push:
    branches: [ main ]
    paths: [ 'Dockerfile', '.github/workflows/build.yml' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      pg_major:
        description: 'PostgreSQL major version'
        required: false
        default: '17'
        type: choice
        options: ['16', '17']
  schedule:
    - cron: '0 2 * * 1'  # 每周一检查更新

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        pg_major: [16, 17]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch,suffix=-${{ matrix.pg_major }}
            type=ref,event=pr,suffix=-${{ matrix.pg_major }}
            type=raw,value=${{ matrix.pg_major }}
            type=raw,value=${{ matrix.pg_major }}-{{date 'YYYYMMDD'}}
            type=raw,value=latest,enable={{is_default_branch}},suffix=-${{ matrix.pg_major }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            PG_MAJOR=${{ matrix.pg_major }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.pg_major }}
          cache-to: type=gha,mode=max,scope=${{ matrix.pg_major }}